import type { AzureResourceSchema } from '@terraformui/shared';
import { schemaRegistry } from '../resources/schema-registry';

interface GenerateOptions {
  extractVariables?: boolean;
  includeProvider?: boolean;
}

interface GenerateResult {
  files: Record<string, string>;
  variables: Array<{
    name: string;
    type: string;
    defaultValue?: unknown;
  }>;
}

class TerraformGenerator {
  async generateSingle(
    type: string,
    name: string,
    configuration: Record<string, unknown>,
    options: GenerateOptions = {}
  ): Promise<GenerateResult> {
    const schema = schemaRegistry.getSchema(type);
    
    if (!schema) {
      throw new Error(`Unknown resource type: ${type}`);
    }

    const files: Record<string, string> = {};
    const variables: Array<{ name: string; type: string; defaultValue?: unknown }> = [];

    // Generate main.tf content
    const mainTf = this.generateMainTf(schema, name, configuration, options);
    files['main.tf'] = mainTf;

    // Generate variables.tf if extractVariables is true
    if (options.extractVariables) {
      const extractedVars = this.extractVariables(schema, configuration);
      if (extractedVars.length > 0) {
        variables.push(...extractedVars);
        files['variables.tf'] = this.generateVariablesTf(extractedVars);
        files['terraform.tfvars'] = this.generateTfvars(extractedVars);
      }
    }

    // Generate outputs.tf
    files['outputs.tf'] = this.generateOutputsTf(schema, name);

    return { files, variables };
  }

  private generateMainTf(
    schema: AzureResourceSchema,
    name: string,
    configuration: Record<string, unknown>,
    options: GenerateOptions
  ): string {
    const lines: string[] = [];

    // Add header comment
    lines.push('# Generated by TerraformUI');
    lines.push(`# Generated at: ${new Date().toISOString()}`);
    lines.push('');

    // Add terraform block
    lines.push('terraform {');
    lines.push('  required_version = ">= 1.0.0"');
    lines.push('');
    lines.push('  required_providers {');
    lines.push('    azurerm = {');
    lines.push('      source  = "hashicorp/azurerm"');
    lines.push('      version = "~> 3.0"');
    lines.push('    }');
    lines.push('  }');
    lines.push('}');
    lines.push('');

    // Add provider block
    if (options.includeProvider !== false) {
      lines.push('provider "azurerm" {');
      lines.push('  features {}');
      lines.push('}');
      lines.push('');
    }

    // Add resource block
    lines.push(`resource "${schema.terraformConfig.resourceType}" "${name}" {`);
    
    for (const [key, value] of Object.entries(configuration)) {
      if (value !== undefined && value !== null) {
        const formattedValue = this.formatValue(value);
        lines.push(`  ${key} = ${formattedValue}`);
      }
    }
    
    lines.push('}');

    return lines.join('\n');
  }

  private formatValue(value: unknown): string {
    if (typeof value === 'string') {
      // Check if it's a variable reference
      if (value.startsWith('var.')) {
        return value;
      }
      // Check if it's a resource reference
      if (value.startsWith('${') && value.endsWith('}')) {
        return value.slice(2, -1);
      }
      // Escape quotes and return as string
      return `"${value.replace(/"/g, '\\"')}"`;
    }

    if (typeof value === 'boolean') {
      return value ? 'true' : 'false';
    }

    if (typeof value === 'number') {
      return String(value);
    }

    if (Array.isArray(value)) {
      const items = value.map(v => this.formatValue(v));
      return `[${items.join(', ')}]`;
    }

    if (typeof value === 'object' && value !== null) {
      const entries = Object.entries(value).map(
        ([k, v]) => `    ${k} = ${this.formatValue(v)}`
      );
      return `{\n${entries.join('\n')}\n  }`;
    }

    return String(value);
  }

  private extractVariables(
    schema: AzureResourceSchema,
    configuration: Record<string, unknown>
  ): Array<{ name: string; type: string; defaultValue?: unknown }> {
    const variables: Array<{ name: string; type: string; defaultValue?: unknown }> = [];

    // Extract common variables
    for (const [key, value] of Object.entries(configuration)) {
      // Skip complex objects
      if (typeof value === 'object' && !Array.isArray(value)) {
        continue;
      }

      // Create variable name
      const varName = key.replace(/([A-Z])/g, '_$1').toLowerCase();
      
      // Infer type
      let type = 'string';
      if (typeof value === 'number') {
        type = 'number';
      } else if (typeof value === 'boolean') {
        type = 'bool';
      } else if (Array.isArray(value)) {
        type = 'list(string)';
      }

      variables.push({
        name: varName,
        type,
        defaultValue: value
      });
    }

    return variables;
  }

  private generateVariablesTf(
    variables: Array<{ name: string; type: string; defaultValue?: unknown }>
  ): string {
    const lines: string[] = [];

    lines.push('# Variable definitions');
    lines.push('');

    for (const variable of variables) {
      lines.push(`variable "${variable.name}" {`);
      lines.push(`  type        = ${variable.type}`);
      if (variable.defaultValue !== undefined) {
        lines.push(`  default     = ${this.formatValue(variable.defaultValue)}`);
      }
      lines.push('}');
      lines.push('');
    }

    return lines.join('\n');
  }

  private generateTfvars(
    variables: Array<{ name: string; type: string; defaultValue?: unknown }>
  ): string {
    const lines: string[] = [];

    lines.push('# Variable values');
    lines.push('');

    for (const variable of variables) {
      if (variable.defaultValue !== undefined) {
        lines.push(`${variable.name} = ${this.formatValue(variable.defaultValue)}`);
      }
    }

    return lines.join('\n');
  }

  private generateOutputsTf(schema: AzureResourceSchema, name: string): string {
    const lines: string[] = [];

    lines.push('# Output definitions');
    lines.push('');

    for (const output of schema.outputs) {
      // Replace 'main' with the actual resource name
      const value = output.value.replace(/\.main\./g, `.${name}.`);
      
      lines.push(`output "${output.name}" {`);
      lines.push(`  value       = ${value}`);
      lines.push(`  description = "${output.description}"`);
      lines.push('}');
      lines.push('');
    }

    return lines.join('\n');
  }
}

export const terraformGenerator = new TerraformGenerator();
